### PR TITLE
Allows more than 50 tips

### LINKED ISSUE #21: Does not build on 64 bit
Welcome to the Haiku shell.

~/HaikuArchives/Tipster> make
mkdir -p objects.x86_64-cc5-release; \
mkdepend  -Iobjects.x86_64-cc5-release/  -Isource/ -p .cpp:objects.x86_64-cc5-release/%n.o -m -f "objects.x86_64-cc5-release/Shuffle.d" source/Shuffle.cpp
mkdir -p objects.x86_64-cc5-release; \
mkdepend  -Iobjects.x86_64-cc5-release/  -Isource/ -p .cpp:objects.x86_64-cc5-release/%n.o -m -f "objects.x86_64-cc5-release/TipsterText.d" source/TipsterText.cpp
mkdir -p objects.x86_64-cc5-release; \
mkdepend  -Iobjects.x86_64-cc5-release/  -Isource/ -p .cpp:objects.x86_64-cc5-release/%n.o -m -f "objects.x86_64-cc5-release/Tipster.d" source/Tipster.cpp
mkdir -p objects.x86_64-cc5-release; \
mkdepend  -Iobjects.x86_64-cc5-release/  -Isource/ -p .cpp:objects.x86_64-cc5-release/%n.o -m -f "objects.x86_64-cc5-release/MainWindow.d" source/MainWindow.cpp
mkdir -p objects.x86_64-cc5-release; \
mkdepend  -Iobjects.x86_64-cc5-release/  -Isource/ -p .cpp:objects.x86_64-cc5-release/%n.o -m -f "objects.x86_64-cc5-release/App.d" source/App.cpp
mkdir -p objects.x86_64-cc5-release; \
mkdepend  -Iobjects.x86_64-cc5-release/  -Isource/ -p .cpp:objects.x86_64-cc5-release/%n.o -m -f "objects.x86_64-cc5-release/AboutTipster.d" source/AboutTipster.cpp
g++ -c source/AboutTipster.cpp -iquote./  -iquoteobjects.x86_64-cc5-release/  -iquotesource/   -O3    -o "objects.x86_64-cc5-release/AboutTipster.o"
g++ -c source/App.cpp -iquote./  -iquoteobjects.x86_64-cc5-release/  -iquotesource/   -O3    -o "objects.x86_64-cc5-release/App.o"
g++ -c source/MainWindow.cpp -iquote./  -iquoteobjects.x86_64-cc5-release/  -iquotesource/   -O3    -o "objects.x86_64-cc5-release/MainWindow.o"
g++ -c source/Tipster.cpp -iquote./  -iquoteobjects.x86_64-cc5-release/  -iquotesource/   -O3    -o "objects.x86_64-cc5-release/Tipster.o"
source/Tipster.cpp: In member function 'void Tipster::UpdateTip()':
source/Tipster.cpp:400:15: error: invalid array assignment
   fRandomSeq1 = fRandomSeq2;
               ^
/boot/system/develop/etc/makefile-engine:291: recipe for target 'objects.x86_64-cc5-release/Tipster.o' failed
make: *** [objects.x86_64-cc5-release/Tipster.o] Error 1
~/HaikuArchives/Tipster>

### PR DESCRIPTION
**Pull request by janus2**
* Fixes 64bit build
* Fixes #21 
* Need some testing

### CODE REVIEW

**Comment by humdingerb** [comment]
Build's under 64bit now (but see issue #23).
Using more than 50 tips works, too.
Thanks!

**Comment by janus2** [comment]
I will look into #23. When I tested it found the file in my case...

**Comment by janus2** [comment]
What is your locale?

**Comment by janus2** [comment]
preferred language

**Pull request merged**
